-- Novas opções de formulário:
--   Tipo de Visita (comoChegou): AGENDAMENTO_SELENA
--   Origem (comoSoube): SITE
-- Status: APLICADA.
ALTER TABLE Visita
  MODIFY COLUMN comoChegou
    ENUM('AGENDADO_CORRETOR','CLIENTE_PASSANTE','AGENDAMENTO_SELENA') NOT NULL;

ALTER TABLE Visita
  MODIFY COLUMN comoSoube
    ENUM('INSTAGRAM','FACEBOOK','WHATSAPP','CORRETOR','PANFLETO','TV','RADIO',
         'STAND_CENTRAL_VENDAS','INDICACAO','OUTDOOR','OBRA',
         'FAIXA_PASSARELA_SAO_CRISTOVAO','GOOGLE','SITE',
         'TV_HOSPITAL_SAO_RAFAEL') NOT NULL;
